name: build image
on:
  push:
    branches:
      - go 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2.12
        with:
          dockerfiles: Dockerfile
          image: ${{ github.repository }}
          tags: go-dev
          extra-args: >
            --timestamp
            0

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build-image.outputs.image }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: go-dev
